travis:
  secure:
    BINSTAR_TOKEN: PKovZAPJff6psE5MInp1ItkXW7YooTvJwrz/XCScOxGZxgsvOOs8f+Hv4UZwwLxSWVUcagbd1bt6FogDCXPXV6v9LAmSG/30zk4DMU7VckFt5eVYewnkkfpJ0IQfYCpL6gLLNL98AEWNAcYSzFIVjyHzvGztN9ETDzkwH1IbKTe4OXUSTZ6oxAHYXmsUQ8bsPUveYZ+RL9dnA7NUhvj8998J27IdESPY+om79qPXWQaAVn0NmQVwUTVIXwBvukhWQLPAJGTNCLb77aRtmVjDa4nPxQYMMsO0nHM0wW1Ae0h2I/xZJqpxT3+vMIHsTrAoCkmyuHZqbe+didzIfbv6j7VUKmRBbya6qFVH/VGlXqcJMPibeRiyp/hngZtwiMkeEF0p90dxSLbdaRCp9phhb78dAIxhTGxUbD0zaWWQdhwjoiRnJbLRXLRG2pXICJx8HgDa5VnBSe7PIH0DQOFXRt8AHiT/nMD3F4K8sQRsXwR/GsDQFNlrf6KPvzdrf2XEFHK4uGj7eHG1FxXIV4kQ/s437djFi7qtZdlTET6Wrop9Oeu9RH4ujD7PEbaavHkTIm95Drq5F+VulTSAf2FsiUwvVhxyk6dF7cygmGlszVzRQ3BadRFTnyn4XOobCHMEciHy4ywxdqIeRf/vNatF0nzr015OKOP3ieVyyaC/leI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
